name: Deploy
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION_CODE_BASE_NUMBER: 1
      ORG_GRADLE_PROJECT_USE_RELEASE_KEY_STORE: true
      ORG_GRADLE_PROJECT_RELEASE_KEYSTORE_PATH: ${{ github.workspace }}/keystore/spaceship-upload-keystore.jks
      ORG_GRADLE_PROJECT_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      ORG_GRADLE_PROJECT_RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Set up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v1

      - name: Set gradle properties
        run: |
          VERSION_CODE=$(($VERSION_CODE_BASE_NUMBER + $GITHUB_RUN_NUMBER))
          echo "ORG_GRADLE_PROJECT_VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "ORG_GRADLE_PROJECT_BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Build release aab
        run: |
          mkdir keystore
          echo "${{ secrets.KEYSTORE }}" | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/keystore/spaceship-upload-keystore.jks
          ./gradlew clean bundleRelease

      - name: Save release archives
        uses: actions/upload-artifact@v2
        with:
          name: release-archive
          path: |
            ./app/build/outputs/bundle/release/app-release.aab

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download aab
        uses: actions/download-artifact@v2
        with:
          name: release-archive
          path: ./output

      - name: Import Google cloud service key
        run: |
          echo "${{ secrets.GCLOUD_SERVICE_KEY }}" | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/gcloud_service_key.json

      - name: Deploy to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ github.workspace }}/gcloud_service_key.json
          packageName: dev.mkeeda.spaceship
          releaseFiles: ./output/app-release.aab
          track: internal
